networks:
  net_p2pmarket:
    driver: bridge

services:
  p2p-market-frontend:
    build:
      context: ../../
      dockerfile: Deployment/Docker/Dockerfile
    container_name: p2p-market-frontend
    ports:
      - "8075:80"
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1.0
    networks:
      - net_p2pmarket